// Curated, public demo metadata. Original Methodenkarten and internal studies are NOT embedded.
export const METHODS = [
  {id:"aktion",title:"Aktionspunkte",minPeople:3,time:"15–30 Min.",why:"Aus einer Idee einen kleinen Versuch mit Zuständigkeiten machen.",steps:["Wählt höchstens fünf konkrete Aufgaben.","Haltet fest, wer was bis wann macht.","Prüft gemeinsam, was ihr daraus gelernt habt."]},
  {id:"empathie",title:"Empathie-Gespräch",minPeople:2,time:"ca. 30 Min.",why:"Die tatsächliche Sicht eines Menschen verstehen.",steps:["Ladet eine Person zu einem offenen Gespräch ein.","Fragt nach einem konkreten Erlebnis und hört zu.","Haltet eine neue Erkenntnis fest, bevor ihr Lösungen entwickelt."]},
  {id:"fragen",title:"Fragen-Landkarte",minPeople:2,time:"ca. 45 Min.",why:"Aus vielen offenen Fragen einen klaren Anfang finden.",steps:["Schreibt eure Herausforderung auf.","Sammelt eure wichtigsten Fragen und ordnet sie.","Wählt die erste Frage aus, die ihr beantworten möchtet."]},
  {id:"beobachten",title:"Beobachten",minPeople:2,time:"60–120 Min.",why:"Den tatsächlichen Arbeitsalltag verstehen, statt Vermutungen zu sammeln.",steps:["Wählt einen konkreten Ablauf und beobachtet ihn gemeinsam.","Notiert, was passiert und welche Fragen auftauchen.","Vergleicht eure Erkenntnisse, bevor ihr etwas verändert."]},
  {id:"acht",title:"Verrückte 8",minPeople:3,time:"ca. 15 Min.",why:"Über die erste, naheliegende Idee hinausdenken.",steps:["Faltet ein Blatt in acht Felder.","Skizziert acht mögliche Ideen in acht Minuten.","Tauscht euch aus und wählt einen kleinen Versuch."]},
  {id:"rollbrett",title:"Rollbretter bauen",minPeople:2,time:"20–30 Min.",why:"Eine grosse Idee mit einem kleinen, greifbaren Versuch prüfen.",steps:["Wählt eine Annahme, die ihr prüfen möchtet.","Baut einen einfachen Versuch mit wenig Aufwand.","Vereinbart, woran ihr erkennt, was ihr gelernt habt."]},
  {id:"skizze",title:"Ideenskizze",minPeople:1,time:"10–15 Min. pro Skizze",why:"Eine Idee sichtbar machen, bevor ihr viel Zeit investiert.",steps:["Notiert, für wen die Idee gedacht ist.","Zeichnet den Nutzen in einer einfachen Skizze.","Holt Rückmeldungen ein und verändert eure Idee."]},
  {id:"annahmen",title:"Annahmen formulieren",minPeople:2,time:"20–30 Min.",why:"Das wichtigste Unbekannte vor dem nächsten Schritt sichtbar machen.",steps:["Schreibt eure wichtigste Annahme als «Wir glauben, dass …» auf.","Überlegt, woran ihr erkennen könnt, ob sie stimmt.","Probiert einen kleinen, risikoarmen Test aus."]},
  {id:"feedback",title:"Strukturiertes Feedback",minPeople:4,time:"15 Min. pro Runde",why:"Einer Idee konstruktive Rückmeldung geben.",steps:["Stellt die Idee in fünf Minuten vor.","Nehmt euch fünf Minuten für Verständnisfragen.","Gebt fünf Minuten Rückmeldung: Was gefällt? Was wünscht ihr euch?"]},
  {id:"challenge",title:"Zentrale Herausforderung definieren",minPeople:3,time:"30–45 Min.",why:"Ein gemeinsames Verständnis für die eigentliche Herausforderung finden.",steps:["Sammelt konkrete Beobachtungen.","Sucht gemeinsame Muster.","Formuliert eine klare Herausforderung und euren nächsten Schritt."]}
];
export const MEDIA = [
  {id:"kmu_innovation",type:"Podcast",title:"Innovation bei KMU – wie geht das?",source:"Radio 1 / ZKB",url:"https://podcasts.apple.com/ch/podcast/innovation-bei-kmus-wie-geht-das/id1633626901?i=1000606736134",about:"Ein Schweizer KMU berichtet über konkrete Innovationserfahrungen."},
  {id:"svc_ki",type:"Videopodcast",title:"KI im KMU – Chancen und konkrete Anwendungen",source:"Swiss Venture Club",url:"https://svc.swiss/de/inspiration/podcast/55-podcast-folge-kmustorys-mit-unternehmer-michael-wegmuller-co-founder",about:"Unternehmergespräch über den praktischen Einsatz von KI."},
  {id:"svc_team",type:"Videopodcast",title:"Handwerk und Firmenkultur",source:"Swiss Venture Club",url:"https://svc.swiss/de/inspiration/podcast-kmustorys",about:"Unternehmergeschichte zur Zusammenarbeit im Handwerksbetrieb; auf der Seite Folge 50 auswählen."}
];
// Medien sind externe Beispiele und vor einem echten Mobiliar Pilot redaktionell zu prüfen.
